version: '3.8'

services:
  server-a:
    build:
      context: ./server-a
    ports:
      - "3000:3000"
    container_name: server-a

  server-b:
    build:
      context: ./server-b
    ports:
      - "3001:3001"
    container_name: server-b


  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    container_name: nginx-lb